### ISSUE TITLE
你能写个教程或者使用说明吗，同学?

### ISSUE THREAD

**Issue by jiespring** [huijiewei/CoreseekDocker#1]
你能写个教程或者使用说明吗，同学?
Can you write a tutorial or instructions, class?
あなたは本を書いたり説明したりすることができますか?学生は?
Pourriez-vous écrire cours sur la manière de les utiliser, ou est-ce que?

**Comment by huijiewei** [comment]
Coreseek 配置文件放在 data/prod 目录
运行使用 coreseek_prod.sh
